server:
  port: 9002
  
spring:
  application:
    name: ATM-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://host.docker.internal:8761/eureka/